### ISSUE TITLE
Error loading pyo from windows 10 with python 3.5 32bits

### ISSUE THREAD

**Issue by carlitoselmago** [belangeo/pyo#103]
I'm trying to make it work on any python3 version, got stuck here.

`Traceback (most recent call last):
  File "02-sine-tone.py", line 7, in <module>
    from pyo import *
  File "C:\Python35-32\lib\site-packages\pyo.py", line 21, in <module>
    import pyolib.analysis as analysis
  File "C:\Python35-32\lib\site-packages\pyolib\analysis.py", line 32, in <module>
    from ._core import *
  File "C:\Python35-32\lib\site-packages\pyolib\_core.py", line 57, in <module>
    from _pyo import *
ImportError: DLL load failed: The specified module could not be found.`

**Comment by belangeo** [comment]
Hi,
Can you try this installer:

https://www.dropbox.com/s/55zcszqcuicrm36/pyo_0.8.6_py2.7_setup.exe?dl=0

There is an error in windows dependencies in version 0.8.6. I'll build new installers soon...

**Comment by carlitoselmago** [comment]
I tried, i still get:

>  File "C:\Python35-32\lib\site-packages\pyolib\_core.py", line 57, in <module>
>     from _pyo import *
> ImportError: DLL load failed: The specified module could not be found.

**Comment by belangeo** [comment]
Oh, sorry, my bad! I gave you the link to the py2.7 installer. The py3.5 installer with the fix is:

https://www.dropbox.com/s/alqhi6kr9pykvqn/pyo_0.8.6_py3.5_setup.exe?dl=0

**Comment by carlitoselmago** [comment]
still getting the same error, I actually end up switching my project to linux and no problem with that there, so if you need to fix the installer for windows take your time, others will benefit. Thanks for the good work! Pyo is amazing!

**Comment by mHo2** [comment]
Hi,

Getting the same issue:

`=== Output log of process "01-audio-server.py", launched: "06 Aug 2017 21:20:52" ===
Traceback (most recent call last):
  File "01-audio-server.py", line 9, in <module>
    from pyo import *
  File "C:\Users\mathe\AppData\Local\Programs\Python\Python36-32\DLLs\pyo.py", line 21, in <module>
    import pyolib.analysis as analysis
  File "C:\Users\mathe\AppData\Local\Programs\Python\Python36-32\DLLs\pyolib\analysis.py", line 32, in <module>
    from ._core import *
  File "C:\Users\mathe\AppData\Local\Programs\Python\Python36-32\DLLs\pyolib\_core.py", line 57, in <module>
    from _pyo import *
ModuleNotFoundError: No module named '_pyo'`

**Comment by belangeo** [comment]
Pyo is compiled against python 3.5. I'm not sure you can run it under 3.6... My plan is to support 3.6 by the end of the summer!

**Comment by belangeo** [comment]
DLL load failed is fixed in sources. Python 3.6 support is another subject. It's in the plan for 0.8.7.

**Comment by sinfloodmusic** [comment]
Hi.  Looks like there's a 0.8.7 binary for python 3.6 on Windows 7+, so I think this is supposed to be resolved.  Unfortunately I'm getting the same error when I try to import pyo.  :(  I'm on Windows 10 64bit, using python 3.6 32 bit.  I tried copying the files around to the DLLs folder like I'd seen mentioned in an older post but still can't seem to get it working.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Program Files (x86)\Python36-32\lib\site-packages\pyo.py", line 21, in <module>
    import pyolib.analysis as analysis
  File "c:\Program Files (x86)\Python36-32\lib\site-packages\pyolib\analysis.py", line 32, in <module>
    from ._core import *
  File "c:\Program Files (x86)\Python36-32\lib\site-packages\pyolib\_core.py", line 57, in <module>
    from _pyo import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by belangeo** [comment]
Why copying the files? Does this mean that the pyo installer did not find your current python installation. It seems to be a system-wide installation, mine is in Users\myuser\AppData\...
If you copy pyo's file, they should all go in the site-packages, and there is a bunch of them. You can get the list of needed files from the installer script (line 38 to 56):

https://github.com/belangeo/pyo/blob/master/installers/win/win_installer_py36.iss

**Comment by sinfloodmusic** [comment]
Hi belangeo.  Correct, it's a system-wide install.  Files 38-56 of that script all seem to have made it to their intended destination, so now I'm really confused.

**Comment by belangeo** [comment]
Maybe this is something related to the system-wide install, Il try to do some tests this week.

**Comment by sinfloodmusic** [comment]
Thank you!  FYI the python install was done by Visual Studio Community 2017.  Based on the add/remove programs it's the standard 3.6 32bit version you'd get from https://www.python.org

I'm going to remove it and try the user-based install from python.org and see if it works for me.

**Comment by sinfloodmusic** [comment]
Removing the global install and replacing it with a user-based install and then re-installing pyo did the trick.  Seems to be something with the global install.

**Comment by belangeo** [comment]
Ok, thanks for trying. It's probably a system-specfic DLL that I need to add in site-packages. I'll investigate.

**Comment by belangeo** [comment]
Is it possible that it's just a permission setting problem? I installed python 3.6 system-wide (no prior install of python 3.6 on this computer), then I installed wxpython with pip and there I had to change the permissions on the Python36 folder to allow pip to write the files. After that I installed pyo 0.8.7 and had no problem to import it, either from the command line or from E-Pyo.

**Comment by mujeebhistorian** [comment]
Hi! belangeo. I'm using Windows 10 64 bit (october 2017 update). The sound button doesn't work. I'm not a programmer but I'm sure, it's related to python. I've installed the 3.6 version. Issue was not solved. Then I installed the 3.7 beta 2 version. Still the problem exists. Please help me, if you can... thanking you in anticipation


![err](https://user-images.githubusercontent.com/37399769/37568301-9199ffc6-2a90-11e8-8c7b-a9726adee984.PNG)

**Comment by belangeo** [comment]
I think you're at the wrong place... This does not concern pyo (the DSP module has nothing to do with python extension .pyo!). Your log is about https://github.com/ciscorn/ldoce5viewer .

**Comment by syfenx** [comment]
test
